# Generated by Django 3.2.7 on 2021-10-04 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_engine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='availbale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='product_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
